services:

  app:
    build:
      target: development
    volumes:
      - ./.yarn:/lvivska/.yarn
      - ./components:/lvivska/components
      - ./pages:/lvivska/pages
      - ./public:/lvivska/public
      - ./styles:/lvivska/styles
      - ./util:/lvivska/util
      - ./tailwind.config.js:/lvivska/tailwind.config.js

  phpmyadmin:
    deploy:
      replicas: 0 # comment-out to use this
    container_name: lvivska-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - database
    ports:
      - '8000:80'
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASS: password
    networks:
      - cms

  wordpress:
    # command: sh -c "/var/www/script/post-deploy.sh && exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf"
    environment:
      WORDPRESS_DEBUG: 1
      WORDPRESS_FS_METHOD: direct
